# Chapter 08 예외처리

## 1. 예외처리(exception handling)

### 1) 프로그램 오류
- `컴파일 에러` : 컴파일 시에 발생하는 에러
- `런타임 에러` : 실행 시에 발생하는 에러
- `논리적 에러` : 실행은 되지만, 의도와 다르게 동작하는 것
- 실행시 발생할 수 있는 프로그램 오류를 `에러`(error)와 `예외`(exception) 두가지로 구분
- `에러` : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- `예외` : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

### 2) 예외 클래스의 계층구조
- Exception, Error 클래스 존재
- `Exception` 클래스 : 사용자 실수와 같은 외적인 요인에 의해 발생하는 예외
- `RuntimeException` 클래스 : 프로그래머의 실수로 발생하는 예외

### 3) 예외처리하기 - try-catch문
- 예외처리의 정의 : 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
- 예외처리의 목적 : 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것
- 하나의 메서드 내 여러개 try-catch문 존재 가능
- try블럭 또는 catch블럭 내에 try-catch문 존재 가능

### 4) try-catch문에서의 흐름
- 예외가 발생하면 발생한 코드에서 catch문으로 이동하게 되며 아래의 문장은 수행되지 않는다

### 5) 예외의 발생과 catch블럭
- 예외가 발생하면 발생한 예외에 대한 클래스가 생성
- 해당 참조변수에 해당하는 catch문을 instanceof 연산자로 찾아가면서 검색
- `printStackTrace()` : 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력
- `getMessage()` : 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다
- 멀티 catch블럭
  - `|` 연산자를 통해 여러개의 에러를 동시에 처리 가능
  ```java
    try {
        ...
    } catch (ExceptionA | ExceptionB e) {
        ...
    }
  ```
  - 연결된 예외 클래스가 조상, 자손 관계라면 에러 발생 → 불필요한 코드 작성을 줄이기 위해

### 6) 예외 발생시키기
- `throw` 키워드를 사용하여 예외 발생
- 예외 가능성이 있는 문장에 대한 예외 처리를 해주지 않으면 `컴파일 에러` → `checked예외`
- 하지만 `RuntimeException`은 프로그래머가 발생시킬 수 있는 에러기 때문에 컴파일 에러는 발생 X → `unchecked예외`

### 7) 메서드에 예외 선언하기
- `throws` 키워드를 사용
- 메서드 선언부에 예외를 선언하여 어떤 예외들이 처리되어야 하는지 알 수 있다
- main 메서드에서도 예외가 처리되지 않으면 main 종료 후 프로그램 종료

### 8) finally블럭
- 발생여부와 상관없이 실행시켜야 될 코드
- try블럭, catch블럭에 `return`문을 만나더라도 finally 수행 후 종료

### 9) 자동 자원 반환 - try-with-resources문
- try 괄호 안에 객체를 생성하는 문장을 넣으면 try 블럭을 벗어나면 `close`를 수행 후 catch나 finally 실행
- 단 자동으로 close가 호출되기 위해서는 `AutoCloseable` 인터페이스를 구현한 클래스여야 한다
- try, finally에서 동시에 예외가 발생하면 try블럭의 예외는 무시
- 두 예외가 동시에 발생할 수 없기에 예외 발생 이후 close에서 예외가 발생한다면 `억제된 예외`로 처리

### 10) 사용자정의 예외 만들기
- 예전에는 checked예외를 만들었지만 현재는 선택적으로 처리할 수 있는 unchecked예외를 만드는 편
  - RuntimeException을 상속받아서 처리

### 11) 예외 되던지기(exception re-throwing)
- catch문에서 필요한 작업 이후 다시 예외를 발생시켜서 던지는 방법

### 12) 연결된 예외(chained exception)
- 예외 A가 예외 B를 발생시켰다면 A를 B의 `원인 예외`라고 한다
- `initCause(e)` : 원인 예외를 등록할 수 있는 함수
- `getCause()` : 원인 예외를 반환하는 함수
- RuntimeException 생성자를 통해 checked예외를 unchecked예외로 변환 가능
  - 유연한 예외 처리 가능